security:
    firewalls:
        navigationrest:
            pattern:                        ^/api/rest/(latest|v1)/(navigationitems|windows|shortcuts)
            provider:                       oro_user
            api:                            false
            http_basic:
                realm: "Secured REST Area"

        main:
            http_basic:
                realm: "Secured REST Area"
            provider: oro_user
            form_login: false
            logout: false
            remember_me: false
            anonymous: true
